export const colorArray = [
    {
        name: 'Default',
        color: {
            bg: '#134e4a',
            primary: '#115e59',
            secondary: '#042f2e',
            caret: '#fb923c',
            text: '#0d9488',
            textActive: '#99f6e4',
            error: '#ff585d',
        },
    },
    {
        name: 'Monokai',
        color: {
            bg: '#272822',
            primary: '#1f201b',
            secondary: '#1f201b',
            caret: '#66d9ef',
            text: '#e6db74',
            textActive: '#e2e2dc',
            error: '#f92672',
            // #a6e22e
        },
    },
    {
        name: 'Solarized Dark',
        color: {
            bg: '#002b36',
            primary: '#859900',
            secondary: '#2aa198',
            caret: '#dc322f',
            text: '#268bd2',
            textActive: '#00222b',
            error: '#d33682',
        },
    },
    {
        name: 'Solarized Light',
        color: {
            bg: '#fdf6e3',
            primary: '#859900',
            secondary: '#2aa198',
            caret: '#dc322f',
            text: '#181819',
            textActive: '#e2d8be',
            error: '#d33682',
        },
    },
    {
        name: 'Dracula',
        color: {
            bg: '#282a36',
            primary: '#bd93f9',
            secondary: '#6272a4',
            caret: '#bd93f9',
            text: '#f8f8f2',
            textActive: '#20222c',
            error: '#f8f8f2',
        },
    },
    {
        name: 'Gruvbox',
        color: {
            bg: '#2e2e2e',
            primary: '#e5b567',
            secondary: '#b4d273',
            caret: '#115e59',
            text: '#99f6e4',
            textActive: '#14b8a6',
            error: '#ff585d',
        },
    },
    {
        name: 'One Dark Pro',
        color: {
            bg: '#2e2e2e',
            primary: '#e5b567',
            secondary: '#b4d273',
            caret: '#115e59',
            text: '#99f6e4',
            textActive: '#14b8a6',
            error: '#ff585d',
        },
    },
    {
        name: 'Tomorrow Night',
        color: {
            bg: '#2e2e2e',
            primary: '#e5b567',
            secondary: '#b4d273',
            caret: '#115e59',
            text: '#99f6e4',
            textActive: '#14b8a6',
            error: '#ff585d',
        },
    },
    {
        name: 'Nord',
        color: {
            bg: '#2e2e2e',
            primary: '#e5b567',
            secondary: '#b4d273',
            caret: '#115e59',
            text: '#99f6e4',
            textActive: '#14b8a6',
            error: '#ff585d',
        },
    },
    {
        name: 'Material Theme',
        color: {
            bg: '#2e2e2e',
            primary: '#e5b567',
            secondary: '#b4d273',
            caret: '#115e59',
            text: '#99f6e4',
            textActive: '#14b8a6',
            error: '#ff585d',
        },
    },
    {
        name: 'Gruvbox Material',
        color: {
            bg: '#2e2e2e',
            primary: '#e5b567',
            secondary: '#b4d273',
            caret: '#115e59',
            text: '#99f6e4',
            textActive: '#14b8a6',
            error: '#ff585d',
        },
    },
    {
        name: 'Palenight',
        color: {
            bg: '#2e2e2e',
            primary: '#e5b567',
            secondary: '#b4d273',
            caret: '#115e59',
            text: '#99f6e4',
            textActive: '#14b8a6',
            error: '#ff585d',
        },
    },
    {
        name: 'Cobalt2',
        color: {
            bg: '#2e2e2e',
            primary: '#e5b567',
            secondary: '#b4d273',
            tertiary: '#99f6e4',
            caret: '#115e59',
            text: '#99f6e4',
            textActive: '#14b8a6',
            error: '#ff585d',
        },
    },
    {
        name: 'Ayu',
        color: {
            bg: '#2e2e2e',
            primary: '#e5b567',
            secondary: '#b4d273',
            tertiary: '#99f6e4',
            caret: '#115e59',
            text: '#99f6e4',
            textActive: '#14b8a6',
            error: '#ff585d',
        },
    },
    {
        name: 'Night Owl',
        color: {
            bg: '#2e2e2e',
            primary: '#e5b567',
            secondary: '#b4d273',
            tertiary: '#99f6e4',
            caret: '#115e59',
            text: '#99f6e4',
            textActive: '#14b8a6',
            error: '#ff585d',
        },
    },
    {
        name: 'Tokyo Night',
        color: {
            bg: '#2e2e2e',
            primary: '#e5b567',
            secondary: '#b4d273',
            tertiary: '#99f6e4',
            caret: '#115e59',
            text: '#99f6e4',
            textActive: '#14b8a6',
            error: '#ff585d',
        },
    },
    {
        name: "SynthWave '84",
        color: {
            bg: '#2e2e2e',
            primary: '#e5b567',
            secondary: '#b4d273',
            tertiary: '#99f6e4',
            caret: '#115e59',
            text: '#99f6e4',
            textActive: '#14b8a6',
            error: '#ff585d',
        },
    },
];
